### ISSUE TITLE
Upgrade to new trace.moe API

### ISSUE THREAD

**Issue by soruly** [rainyroads/twitter-saucenao#68]
Hi, just want to notify you the new trace.moe API is out.
Please take a look and update your program, otherwise it will be broken when the old API deprecates.
You can find the docs of the new API with migration guide at https://github.com/soruly/trace.moe-api

**Comment by FujiMakoto** [comment]
@soruly How does the new media API work? I tried to generate a URL with it but it's not clear,

````
https://media.trace.moe/video/98292/New%20Game!!%20-%2003%20(BD%201280x720%20x264%20AACx2).mp4?t=98292&token=xxx&size=l
```
Is it because my token is no longer valid?

**Comment by soruly** [comment]
Yes the new API response has the full URL, so you don't need to construct the url youself.
